"""added profile_pic

Revision ID: 01b97c9d588f
Revises: f99a779b38f7
Create Date: 2023-02-07 10:23:04.478214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b97c9d588f'
down_revision = 'f99a779b38f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=500), nullable=True))
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
