"""R

Revision ID: f99a779b38f7
Revises: d6c22734f405
Create Date: 2023-02-05 15:03:33.524430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99a779b38f7'
down_revision = 'd6c22734f405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
